[package]
name = "shared_structs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
glam = { version = "0.24.2", default-features = false, features = ["bytemuck", "libm"] }
spirv-std = "0.9.0"